version: '3'

services:
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    restart: on-failure
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb_container
    build:
      context: ./database/postgres
      dockerfile: Dockerfile
    env_file:
      - ./database/postgres/.env.prod
    restart: on-failure
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

volumes:
  postgresdb-data: